export const SAVE_CLIENTE_REQUEST = 'SAVE_CLIENTE_REQUEST';
export const FETCH_CLIENTE_REQUEST = 'FETCH_CLIENTE_REQUEST';
export const UPDATE_CLIENTE_REQUEST = 'UPDATE_CLIENTE_REQUEST';
export const DELETE_CLIENTE_REQUEST = 'DELETE_CLIENTE_REQUEST';
export const CLIENTE_SUCCESS = 'CLIENTE_SUCCESS';
export const CLIENTE_FAILURE = 'CLIENTE_FAILURE';